name: Automated Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # 外部依存なし（標準ライブラリのみ使用）

      - name: Run comprehensive tests
        run: python test_comprehensive.py

      - name: Run smoke tests
        run: python test_smoke.py

      - name: Test summary
        if: always()
        run: |
          echo "==================================="
          echo "Test execution completed"
          echo "==================================="
